name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Deploy API Worker
      working-directory: ./workers/api-worker
      run: pnpm run deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    - name: Deploy Frontend
      working-directory: ./frontend
      run: pnpm run deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        VITE_API_URL: https://api-worker.mborishall.workers.dev

    - name: Deployment Summary (Console)
      run: |
        echo "🚀 Deployment completed!"
        echo "📱 Frontend: https://ukoly-monorepo.mborishall.pages.dev"
        echo "⚡ API Worker: https://api-worker.mborishall.workers.dev"

    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const deploymentInfo = `## 🚀 Deployment Preview

          Your changes have been deployed successfully!

          ### 🔗 Preview Links:
          - **📱 Frontend**: https://ukoly-monorepo.mborishall.pages.dev
          - **⚡ API Worker**: https://api-worker.mborishall.workers.dev

          ### 🧪 Test Your Changes:
          You can test the code execution platform with all 6 languages:
          - JavaScript, Python, C++, C, Rust, Java

          ---
          *Deployment completed at ${new Date().toISOString()}*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: deploymentInfo
          });

    - name: Update PR Status
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'success',
            target_url: 'https://ukoly-monorepo.mborishall.pages.dev',
            description: 'Deployment successful',
            context: 'deployment/preview'
          }); 